language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  # optional
  - jruby-19mode
  - rbx-19mode
  - rbx-2

env:
  - INTEGRATION=openldap

install:
  - if [ "$INTEGRATION" = "openldap" ]; then ./script/install-openldap; fi
  - bundle install

script: bundle exec rake ci

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
    - rvm: rbx-2
  fast_finish: true

notifications:
  email: false
